services:
  - type: web
    name: neurawatch-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://neurawatch-backend.onrender.com
        sync: false

